### ISSUE TITLE
[SETTING] 프로젝트 셋팅

### ISSUE THREAD

**Issue by sung-silver** [nonsoolmate/NONSOOLMATE-SERVER#1]
## 📝 Desciption

- 논술메이트 서버 프로젝트 셋팅

## 📝 To-do

- [x] 프로젝트 생성 및 패키지 구조 공유(도메인 형)
- [x] 프로젝트 내 필요한 의존성 추가
- [x] gitignore에 환경설정 파일 추가
- [x] swagger 설정 코드 추가    

## 📝 ETC

- 마감: 1/2(화)
