### ISSUE TITLE
[FEAT] Swagger 에러 적용 및 DTO에 설명 추가 

### ISSUE THREAD

**Issue by sung-silver** [nonsoolmate/NONSOOLMATE-SERVER#106]
## 📝 Desciption

- Swagger에서 각 컨트롤러 별로 에러를 추가하고, DTO에 설명을 추가합니다
- ApiResponse import 경로 적용되어 있는 부분을 수정합니다(SuccessResponse, ErrorResponse로 ApiResponse가 변경됨에 따라 더이상 클래스 이름이 중복되지 않습니다)

## 📝 To-do

- [ ] 컨트롤러 별 에러 추가
- [ ] RequestDTO, ResponseDTO에 스웨거 적용
- [ ] (Swagger 내)@ApiResponse import 경로 삭제 

## 📝 ETC

- 마감: 2024.01.17(수)
