### ISSUE TITLE
[REFACTOR] 파트장 피드백 내용 반영

### ISSUE THREAD

**Issue by sung-silver** [nonsoolmate/NONSOOLMATE-SERVER#19]
## 📝 Desciption

- style: 패키지 구조 분리
- refactor: 엔티티에서 불필요한 어노테이션 제거
- refactor: ResponseEntity안에 ApiResponse를 넣어 컨트롤러에서 상태값 맞추어주기
- fix: 토큰 발급 responsebody에 담아 넘기기

## 📝 To-do

- [x] style: 패키지 구조 분리
- [x] fix: 엔티티에서 불필요한 어노테이션 제거
- [x] refactor: ResponseEntity안에 ApiResponse를 넣어 컨트롤러에서 상태값 맞추어주기
- [x] refactor: 토큰 발급 responsebody에 담아 넘기기

## 📝 ETC

- 마감: 2024.01.08 (월)
