### ISSUE TITLE
[FIX] AWS 최신 의존성에 따른 코드 수정 및 AWSService validateURL 함수 수정

### ISSUE THREAD

**Issue by sung-silver** [nonsoolmate/NONSOOLMATE-SERVER#56]
## 📝 Desciption

- AWS Service에서 validateURL 함수의 로직 및 에러 핸들링을 수정합니다

## 📝 To-do

- [x] AWS 최신 의존성에 따른 CloudFrontService 코드 수정
- [x] validateURL 함수 수정
- [x] validateURL 에러핸들링 수정

## 📝 ETC

- 마감: 2024.01.12(금)
