### ISSUE TITLE
[FIX] UniversityExamImage 엔티티 수정 및 대학 시험 문제 반환 시 페이지 번호 오름차순으로 반환

### ISSUE THREAD

**Issue by sung-silver** [nonsoolmate/NONSOOLMATE-SERVER#64]
## 📝 Desciption

- UniversityExamImage 엔티티 수정(page 필드 추가)
- 대학 시험 문제 반환 시(ex. 시험보기: 문제보기) 페이지 번호 오름차순으로 반환

## 📝 To-do

- [x] UniversityExamImage 엔티티 int형으로 page 필드 추가
- [x] schema.sql에서 university_exam_image 테이블 수정
- [x] 대학 시험 문제 반환 시(ex. 시험보기: 문제보기) 페이지 번호 오름차순으로 반환

## 📝 ETC

- 마감: 2024.01.12(금)
