### ISSUE TITLE
[FEAT] ApiResponse, CustomError Handler 구현

### ISSUE THREAD

**Issue by sung-silver** [nonsoolmate/NONSOOLMATE-SERVER#7]
## 📝 Desciption

- 공통 ApiResponse를 만듭니다
- Custom Error Handling을 합니다
- REFACTOR: 도메인형에 맞추어 해당 패키지 중 도메인을 domain 패키지 안에 모아두는 방식으로 리팩터링합니다

## 📝 To-do

- [x] ApiResponse 만들기
- [x] Custom Error Handling
- [x] 패키지 구조 조금 수정
- [x] db 연결 후 yml 노션에 공유
