### ISSUE TITLE
[FIX] dev test에 따른 수정 사항 (성은 API)

### ISSUE THREAD

**Issue by sung-silver** [nonsoolmate/NONSOOLMATE-SERVER#70]
## 📝 Desciption

- dev 테스트에서 발견된 응답값 필드명이 다른 부분을 수정합니다

## 📝 To-do

- [x] 목표 대학 시험 리스트에서 시험 id가 universityId로 전달되는 것 수정
- [x] 시험 보기: 시험 이름 & 제한 시간에서 SuccessType message를 `대학 시험 정보 조회에 성공했습니다` 로 수정
- [x] 시험 보기: 시험 이름 & 제한 시간에서 `/university/exam/info/{id}` -> `/university/exam/{id}/info` 로 경로 수정

## 📝 ETC

- 마감: 2024.01.13(토)
